= Planung
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]

== Ausgangssituation in SE II

=== Teamaufstellung 

Am Anfang des Semesters wurde das Team von {ab} und {tki} leider verlassen. Deshalb wurde uns {pg} als Verstärkung zugewisen. Dadurch haben wir am Angang des Semester zu erst eine neu Einteilung der Rollen des Teams durchgeführt. Diese ist genauer in der Rollenübersicht einzusehen. LINK!!!!

=== Aufgabenstellung und Auftraggeber 

Die Aufgabenstellung änderte sich nicht zu SE I, es war unsere Aufgabe auf dem existierenden System ein Buchungssystem zu integrieren und Bugs des vorhanden Systems zu beheben. Auch unser Auftraggeber Herr Matthias Heisig blieb identisch zu SE I. 
Allerdings änderte er gleich beim ersten Themenersteller-Meeting die Aufgaben-Priorisierung.
Es war von unsere Seite eigentlich geplant das erst die Use Cases nacheinander implemtiert werden und anschlißend ein Zeitfenster eingerichtet wird für Bugfixing und Änderungen des aktuellen Systems. Dies wurde verworfen. 
Durch den Kunden war nun gewünscht, dass nach der Implementierung des Buchungssystems direkt ein besserer Weg gefunden wird, die Geräte im vorhanden System auszuwählen. Die andren Arbeiten sollten dann nach gewohnter Priorisierung aus SE I erfolgen. Eine genaue Auflistungen der Aufgaben ist in der Vision zu finden. LINK!!!

== Projektorganisation 

=== Team 

Da wir schon früh in SE I die Erfahrung gemacht haben, das ein gutes Team der Schlüssel zu einem guten Projektabschluss ist haben wir auch in SE II dran festgehalten. Wir meinen mit gutem Team nicht, dass die einzelnen Teammitglieder über große Expertisen im Bereich Software Engineering oder andre IT bezogene Qulifikationen verfügen müssen, sondern wir wollen hier zum Ausdruck bringen, dass eine gute Gruppendynamik und ein starker Zusammenhalt inerhalb der Gruppe für uns wichtig war. 

Wir haben versucht die Planung der einezlnen Teilaspekte so zu gestalten, das die eben genannten Eigenschaft stehts in hohem Ausmaß vorhanden sind. 

[%header, cols="1,2"]
|===
|Eingesetzte Praktik
|Gewünschter Erfolg
|Risiko des Scheiterns miteinbeziehen 
|Die Priorisierung, der Reihenfolge der Arbeitsschritte wurde stets so gewählt, dass ein auftretendes Problem nie die Arbeit der anderen Gruppenmitglieder behinderte. So sollte der Erfolgsdruck gemindert werden.
|Aufgabengebiete weit streuen
|Es wurde versucht die einzlnen Gruppenmitglieder, Rollenunabhänig, in allen Teilgebieten mit kleinen Aufgaben einzusetzen. Hintergrund dieser Strategie war, dass jedes Gruppenmitglied auch die Aufgaben der anderen Rollen kennlernen kann und so auch außerhalb der eigenen Rolle Erfahrungen sammelen konnte.
|Zeit für Austausch einplanen 
|Durch geregelte Gruppendiskussionen kann jedes Mitglied seine Meinung oder Erfahrung bei Entscheidung miteinbringen und sollte dadruch auch mehr am Projekt beteiligt werden
|Demokratische Entscheidungsfindung
|Jede Entscheidung die von unsere Stelle getroffen werden konnte wurde demokratisch und nicht autoritär entschiden. Dies sollte gewährleisten, dass alle Gruppenmitglieder mit der Entscheidung einverstanden sind und auch keine schlechten Entscheidungen, wie z.B. durch mangelhafte Expertise, getroffen werden.
|Einsetzen eines QMs und Puls-Checks
|Durch Verwendung eines Qualitätsmanagements und Puls-Check-Umfragen konnte in der Planung, das allgemeine Gruppenempfinden miteinebzogen werden. Hier sollten mögliche Probleme durch gezielte Fragen oder Austausch gelöst werden können. (Hinweis: es wurden alle Probleme stets anonymisiert gesammelt und die Disskusionsgrundlage allgemein formuliert)
|Stundennachweis
|Die Gruppenmitglieder wurden dazu angehalten, ihre Arbeitszeiten in einer Stundenliste zu protokolieren. So sollte in der Planung sichergestellt werden, das eine gleichmäßige Verteilung der Arbeitszeit über alle Gruppenmitglieder statt finden kann. 
|===


=== Rollenverteilung 


Wiederkehrende Aufgaben standalisieren:

Immer wiederkehrnde kleine Aufgaben wie z.B. das erstellen einer Agenda für das Weekly wurden, direkt ohne Dokumentation in der Work-Item-List ausgeführt oder wurden als durchgehender Issue aufgeführt. Dies sollte ermöglichen, dass die Work-Item-List übersichtlicher angezeigt werden konnte, troz teilweiser sehr granularen Aufgliederung von großen Aufgaben. 