= Qualitätsmanagement
Alena Bischoff <alena.bischoff@htw-dresden.de>; Gregor Müller <gregor.mueller@htw-dresden.de>; Julius Schmidt <juliusheiko.schmidt@htw-dresden.de>; Richard Böhme <richard.boehme@htw-dresden.de>; Taejun Kim <taejun.kim@htw-dresden.de>; Tim Würzburg <tim.wuerzburg@htw-dresden.de>; Tobias Karsch <tobias.karsch@htw-dresden.de>; William Elsner <william.elsner@htw-dresden.de>;
{localdatetime}
include::../../_includes/default-attributes.inc.adoc[]


== Hintergrund 

Unser Ziel war es, ein Projekt zu verwirklichen, was auf der einen Seite alle Stakeholder zufriedenstellt, aber auch vor allem die hohen Qualitätsanforderungen der Gruppe widerspiegelt. Deshalb entschlossen wir uns sehr früh ein *Qualitätsmanagement* zu gründen, dass einzelnen Arbeitsschritte, Dokumentationsarbeiten und die Kommunikation der Gruppe überwacht.

Aus diesem Grund wurde von {AB} und {GM} ein Regelwerk formuliert, nachdem das QM die oben aufgezählten Punkte bewerten kann. Zusätzlich wurden hier auch Anhaltspunkte für die Test Cases und den Umgang mit GitHub festgehalten. Anschließend wurde {AB} mit der Aufgabe betraut, das QM zu führen und auf Regelverstöße aufmerksam zu machen. Auch wurde in jedem Weekly durch kurzes Nachfragen durch die Projektmanager überprüft, ob das QM auf Probleme aufmerksam wurde.

In SE II übernahm die Rolle des QM-Beauftragten {GM}, da {AB} leider aus dem Projekt ausschied. Da {GM} auch die Rolle des Projektmanagers innehat wurde in den folgenden Dokumente darauf verzichtet zu erwähnen das PM und QM zusammenarbeiteten oder gegenseitige Berührungspunkte hatten, die aber natürlich stattgefunden haben. 

Damit das QM nicht nur auf eigene Beobachtungen in seinen Bewertungen zurückgreifen musste, wurden an jedem Iterationsende eine Umfrage durchgeführt die dem Schema der Umfrage aus SE I folgte. Der Fragenkatalog wurde allerdings um die Hälfte reduziert um die Bearbeitungszeit kürzer zu gestalten. 

Durch den starken Rückgang von Teammitgliedern auf vier Personen wurde in den Meetings auf einen Redeführer verzichtet. Dies hatte natürlich Auswirkungen auf den Gesprächs- und Diskussionsablauf. Auch die Tatsache der Corona geschuldeten Online-Meetings trugen dem Kriterium des "ausreden lassen" nicht positiv bei, da man hier nicht immer abschätzen konnte ob das Gegenüber nun fertig war oder nicht. Dennoch wurde am Verzicht des Redeführers standgehalten, da er in seiner Funktion eines geregelten Informationsaustausches bei dieser kleinen Anzahl an Personen mehr störend als hilfreich betrachtet wurde. Somit konnte der positive Schnitt des QM im Punkt "ausreden lassen" nicht gehalten werden, was aber dennoch nicht als störend von der Gruppe aufgenommen wurde. Diese Beobachtung ergibt sich aus den Iterationsumfragen. 

Da das Projekt im Laufe von SE II die Construction Phase erreichte wurde auch eine Programmierkonvention im Regelwerk des QM integriert. Diese wurde von {RB} ausgearbeitet und von den Developern beachtet. Sie sollte die Lesbarkeit von Code verbessern und somit die Arbeit von unterschiedlichen Developern erleichtern. 


<<<
include::qm_rules.adoc[]

<<<
include::qm_review.adoc[]

