= Glossar: Experimenteverwaltung I2
Alena Bischoff <alena.bischoff@htw-dresden.de>; Gregor Müller <gregor.mueller@htw-dresden.de>; Julius Schmidt <juliusheiko.schmidt@htw-dresden.de>; Richard Böhme <richard.boehme@htw-dresden.de>; Taejun Kim <taejun.kim@htw-dresden.de>; Tim Würzburg <tim.wuerzburg@htw-dresden.de>; Tobias Karsch <tobias.karsch@htw-dresden.de>; William Elsner <william.elsner@htw-dresden.de>;
{localdatetime}
include::_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

== Einführung
In diesem Dokument werden die wesentlichen Begriffe aus dem Anwendungsgebiet (Fachdomäne) des EMS definiert. Zur besseren Übersichtlichkeit sind Begriffe, Abkürzungen und Datendefinitionen gesondert aufgeführt.


=== Begriffe
[cols="20,~,~"]
|===
|Term|Definition/ Bedeutung |Synonym

|Kunde
a|* Auftraggeber des Projekts, vorrangiger Stakeholder 
* Betreiber des Verwaltungssystem
* Hr. Heisig
a|* Themensteller

|Dozent
a|* Nutzer des Buchungssystems
* "Kunde des Kunden"
a|* User

|Admin
a|* Gleichzusetzten mit "Kunde"
|

|Bestellung
a|* Anforderung eines Versuchsaufbaus mit Durchführung zur einer festgelegten Zeit
|

|Warenkorb
a|* Temporärer Sammelspeicher für bestellte Experimente pro Dozent
* Bestellübersicht mit Datums- und Zeitauswahl
a|* Bestellzusammenfassung

|Template
a|* Englisch für Vorlage/ Schablone
|

|Wochenplan
a|* Übersicht aller Bestellungen und der Termine der Bereitstellung und Durchführung für die Folgewoche
a|* Wochenübersicht

|Buchungseinsicht
a|* Übersichtliche Dokumentation zur EInsicht der Bestelldetails
* Ergänzund zum Wochenplan
|

|Historie
a|* Häufigkeit der vergangenen Buchungen pro Experiment
a|* Anzahl der Buchungen pro Experiment
* Statistik
* Auswertung

|Frontend-Benutzer
a|* Nutzer der  öffentlich erreichbaren Weboberfläche
* Gleichzusetzen mit "Dozent"
a|* User

|Karteikarte
a|* analoges Abbild der Versuchs-/ Experimentdetails als Alternative zum Tablet/ Webbrowser
a| * Versuchsübersicht

|Virtuelle Maschine
a|* Softwaretechnische Kapselung eines Rechnersystems innerhalb eines lauffähigen Rechnersystems
a|* Testbereich des Systems
* Abkürzung:  VM
* Betreuung durch TAVM

|Open Unified Process
a|* Vorgehensmodell
* siehe https://www2.htw-dresden.de/~anke/openup/index.htm
* _OpenUP is a lean Unified Process that applies iterative and incremental approaches within a structured lifecycle_
a|* Vorgehendmodell
* OpenUP

|===


=== Abkürzungen und Akronyme
[cols="20,~,~"]
|===
|Abkürzung|Bedeutung|Erläuterung

|VM
|Virtuelle Maschine
|siehe Term _Virtuelle Maschine_ in _Begriffe_

|TAVM
|Technischer Ansprechpartner für VM
|hornoff@htw-dresden.de Kontaktverantwortlicher: Richard Böhme

|OpenUP
|Open Unified Process
|siehe Term _Open Unified Process_

|LCO
|Life Cycle Objective Milestone
|siehe project_plan _4. Meilensteine und Ziele_

|TS
|Themensteller
|Siehe Term _Kunde_

|TS-Mx
|Themensteller-Meeting Nr. x
|Bezeichnung für ein Treffen mit dem Themensteller, fortlaufende Nummerierung

|QM
|Qualitätsmanagement
|Interne Sicherung der Qualität in Zusammenarbeit und im Ergebnis

|AQM
|Ansprechpartner QM
|=Alena Bischoff

|===


=== Verzeichnis der Datenstrukturen
[cols="20,30,10,30,10"]
|=== 
|Bezeichnung |Defninition |Format| Gültigkeitsregeln | Aliase

|Anmeldedaten 
|Zusammensetztung von Benutzername und Passwort
|String
|E-Mail-Adresse muss `@`-Zeichen und Punkt enthalten
|Login

|===
