= System-Wide Requirements: {project-name}
Alena Bischoff <alena.bischoff@htw-dresden.de>; Gregor Müller <gregor.mueller@htw-dresden.de>; Julius Schmidt <juliusheiko.schmidt@htw-dresden.de>; Richard Böhme <richard.boehme@htw-dresden.de>; Taejun Kim <taejun.kim@htw-dresden.de>; Tim Würzburg <tim.wuerzburg@htw-dresden.de>; Tobias Karsch <tobias.karsch@htw-dresden.de>; William Elsner <william.elsner@htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
 
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt <Thema> spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. [hier ggf. Verweis einfügen]

NOTE: "To write a good requirement, you must write it as a complete sentence, with a subject and a predicate (usually a verb). The subject is an Actor, a stakeholder, the system under development, or a design entity that is related to the requirement. The predicate specifies a condition, action, or intended result that is done for, by, with, or to the subject."
- (OpenUP; siehe https://www2.htw-dresden.de/~anke/openup) 

NOTE: Unsere Anforderungen sollen den Projekterfolg garantieren. Je gewissenhafter wir sie ausarbeiten und pflegen, desto besser wird das Endprodukt. 

NOTE: Aussagen des ESSENCE Kernel: 
Opportunity focuses on Requirements. 
Requirements set scopes & constraints for work. 

NOTE: Anforderungsanalyse ist Teil der Solution, damit essentieller Teil der Lösung. 
Stakeholder haben Anforderungen. Ziele der Stakeholder sind Teil der Anforderungsspezifikation! 

== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz

* *SWFA-1*: Das System muss dem Dozenten die Möglichkeit bieten, vorgefertigte Experimente mit Datum, Zeit, Studiengang und Kommentar für eine konkrete Vorlesung buchen zu können.

* *SWFA-2*: Das System muss durch Rollenzugehörigkeit sicherstellen, dass die Anwender nur auf entsprechende Bereiche und Funktionalitäten Zugriff haben. 

* *SWFA-3*: Das System muss die bereits gebuchten Experimente aus Vergangeneheit und Gegenwart für sämtliche Rollen spezifisch darstellen können. 

* *SWFA-4*: Das System muss gewährleisten, dass jeder Anwender nur auf den persönlichen Bereich Zugriff hat. Realisiert wird dies durch separate Log-In-Zugänge.  

* *SWFA-5*: Das System muss die Auswertungen von Buchungszahlen in Form von Statistiken ermöglichen. Dies muss der Materialplanung dienlich sein. 

* *SWFA-7*: Das System muss die eingegeben Experimente-Buchungen persistent auf eine (existierende) Datenbank speichern. (Datenverlust muss ausgeschlossen werden.) 

* *SWFA-8*: Das System muss sicherstellen, dass nur valide Angaben getätigt werden können. 

* *SWFA-9*: Das System muss Buchungsfortführungen nach Verbindungsabbrüchen gewährlesiten. Dies wird durch ein Session-Token sichergestellt. 

* *SWFA-10*: Das System muss das Erstellen und Verwalten von Anwenderzugängen durch den Admin gewährleisten. 

== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

* *NFAU-1*: Buchung, Journalverwaltung und Dozentenwochenausgabe müssen übersichtlich, eindeutig und verständlich sein.  

** *NFAU-1.1*: Die Anzahl an Buttons und Interaktionselementen soll gering und komprimiert sein.  

*** Es soll jeweils nur einen Button pro Aktion geben (Bsp.: Warenkorb-Icon zum Buchen, “Buchungen kopieren” zur Direktübernahme vergangener Buchungsverläufe). 

** *NFAU-1.2*: Die Auswahlmenüs zur Detailfestlegung müssen verständlich und inhaltlich komprimiert sein.  

*** Es soll vorgefertigte Drop-Down Menüs und Widgets zur Auswahl des Studiengangs, des Datums, der Vorlesungszeit geben. Die Auswahlmöglichkeiten sollen dabei schon feststehen. Zur Überprüfung wird getestet, ob invalide Eingaben möglich sind. 

** *NFAU-1.3*: Ein Buchungs- und Druckdurchlauf (inkl. Änderung) muss einfach erfassbar und anwendbar sein.  

*** Es soll auf Anglizismen und Fachterminologie verzichtet werden. Große informatische und technische Kenntnisse dürfen nicht zur Bedienung erforderlich sein. Zur Überprüfung wird eine themenfremde Testperson die Abläufe durchgehen. 

** *NFAU-1.4*: Die Möglichkeiten für Fehlentscheidungen oder Orientierungslosigkeit sollen minimiert werden. 

*** Die Dozenten sollen für eine Buchung maximal 10 Klicks (von Anmeldung bis „Buchungsabschluss“) benötigen. Temporär nicht verfügbare Interaktionsmöglichkeiten sollen ausgegraut werden. Fehlermeldungen sollen eindeutig, ohne Interpretationsspielraum und minimal sein.  

* *NFAU-2*: Texte und Schaltflächen sollen auf ca. 50cm Entfernung leicht lesbar und erkennbar sein. 

*** Text muss eine passende Größe und schonende, sowie leserliche Farbe aufweisen.  

*** Schaltflächen und Symbole müssen von guter grafischer Qualität und scharf sein.  

* *NFAU-3*: Die Eingabemöglichkeit der Buchungsdetails soll nicht als Pop-up-Eingaben erscheinen. 

*** Die Buchungsdetails (Studiengang, Vorlesungszeit) sollen vor der eigentlichen Experimentauswahl einmalig eingegeben werden. Zur Überprüfung wird die Anwendung auf das Vorhandensein von Pop-up-Fenstern getestet.  

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

* *NFAR-1*: Das System darf aufgrund von Netzwerkausfällen keinen Schaden nehmen. 
** Test: Verbindungsabbruch erzwingen beim Buchen 

=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

* *NFAR-2*: Die Nutzbarkeit muss gewährleistet sein, wenn alle derzeitigen Anwender gleichzeitig arbeiten wollen. Es darf diesbezüglich keine Begrenzung an parallelen Log-Ins geben.  

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.

* *NFAS-1*: Das Entwicklerteam muss eine (fortgeführte) Entwicklerdokumentation bereitstellen, welche Wartungg und Weiterentwicklung des Systems ermöglicht. 

== Zusätzliche Anforderungen
=== Einschränkungen

* Die Verwaltung des Sourcecodes und der Dokumentation muss mittels *GitHub*  erfolgen. 
* *Ruby on Rails* stellt das hauptsächlich zu nutzende Framework dar. 
* Folgende Programmiersprachen sind weiterhin vorgegeben: 
** *Ruby*   
** HTML/ Slim
** Sass 
** JavaScript 
* Die Software muss durch folgende Browser unterstützt werden: 
** Edge 
** Internet Explorer (Version 11) 
** Chrome
** Firefox 
* Die Softwarelösung soll nur einen handelsüblichen Computer benötigen, auf dem ein entsprechender Browser in der aktuellsten Version installiert ist. 

=== Interface Requirements 
* Die Benutzeroberfläche soll gängige Symbole wie einen Einkaufswagen für den Warenkorb verwenden. 
* Deutsche Bezeichnungen sollen reichen (siehe Usability).
* Das Design soll an der bereits bestehenden Anwendung orientiert sein. 
* Eine offene Menüführung muss gewährleistet sein. Interaktionselemente und Links sollen nicht unnötig in Menüs versteckt sein. 


=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Der Kunde muss über eine mögliche Speicherung von Nutzungsdaten informiert werden.
* Eine etwaige Datenschutzerklärung muss beim Login vorliegen und vor der Nutzung durch Dozenten anerkannt werden. Der Verantwortliche hierbei sollte der Admin sein. 
* Keine fremden Werke dürfen fälschlicherweise als Eigene ausgewiesen werden. Urheberrecht ist zu beachten, gegebenenfalls müssen eigene Grafiken erstellt werden. 
