= System-Wide Requirements: {project-name}
Alena Bischoff <alena.bischoff@htw-dresden.de>; Gregor Müller <gregor.mueller@htw-dresden.de>; Julius Schmidt <juliusheiko.schmidt@htw-dresden.de>; Richard Böhme <richard.boehme@htw-dresden.de>; Taejun Kim <taejun.kim@htw-dresden.de>; Tim Würzburg <tim.wuerzburg@htw-dresden.de>; Tobias Karsch <tobias.karsch@htw-dresden.de>; William Elsner <william.elsner@htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
 
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt {project-name} spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* Zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten <<Use-Case Model: {project-name}, Use-Case Model>>

NOTE: "To write a good requirement, you must write it as a complete sentence, with a subject and a predicate (usually a verb). The subject is an Actor, a stakeholder, the system under development, or a design entity that is related to the requirement. The predicate specifies a condition, action, or intended result that is done for, by, with, or to the subject."
- (siehe https://www2.htw-dresden.de/~anke/openup[OpenUP]) 

NOTE: Unsere Anforderungen sollen den Projekterfolg garantieren. Je gewissenhafter wir sie ausarbeiten und pflegen, desto besser wird das Endprodukt. 

NOTE: Aussagen des ESSENCE Kernel: 
Opportunity focuses on Requirements. 
Requirements set scopes & constraints for work.

NOTE: Anforderungsanalyse ist Teil der Solution, damit essentieller Teil der Lösung. 
Stakeholder haben Anforderungen. Ziele der Stakeholder sind Teil der Anforderungsspezifikation! 

== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz

* *SWFA-1*: Das System muss Zugriffsbeschränkungen gewährleisten, da nicht jeder Anwender jeden Use Case ausführen darf. Diese Zugriffsbeschränkungen erlauben es dem Anwender, nur für ihn vorgesehene Funktionen auszuführen und nur auf für ihn zugängliche Daten zuzugreifen. Dafür ist eine Zuordnung aller Anwender zu Rollen und einem Login notwendig.

** Zu Überprüfungszwecken wird anhand von Test-Logins versucht auf fremde Daten und Rollenfunktionalitäten zuzugreifen

* *SWFA-2*: Das System muss Buchungs- und Anwenderdaten persistent speichern. 

** Überprüfbar wird dies durch Einfügen von Daten. Nach einem Neustart des Systems ist es notwendig, dass die Daten weiterhin vollständig sind

// * *SWFA-8*: Das System muss sicherstellen, dass nur valide Angaben angenommen werden können. 

* *SWFA-3*: Das System muss Zugangsdaten der Anwender vor Diebstahl schützen. 

** Überprüfbar wird dies durch einen Versuch, Testzugangsdaten auszulesen

// * *SWFA-9*: Das System muss Buchungsfortführungen nach Verbindungsabbrüchen gewährleisten. Dies wird durch einen Session-Token sichergestellt. 


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

* *NFAU-1*: Alle Prozesse und Datenausgaben müssen übersichtlich, eindeutig und verständlich sein.

** *NFAU-1.1*: Die Anzahl der Interaktionselemente soll komprimiert sein.

*** Es soll jeweils nur eine Schaltfläche pro Aktion geben (Bsp.: Warenkorb-Icon zum Buchen). Zu Überprüfungszwecken werden alle Interaktionselemente in ihrer Funktion verglichen. 

** *NFAU-1.2*: Die Auswahlmenüs zur Detailfestlegung müssen verständlich und inhaltlich komprimiert sein.

*** Es soll vorgefertigte Drop-Down-Menüs und Widgets zur Auswahl aus von festgelegten Wertebereichen geben. Zur Überprüfung wird getestet, ob invalide Eingaben möglich sind. 

** *NFAU-1.3*: Die Anwendung (inkl. Änderung) muss einfach erfassbar und nutzbar sein.

*** Es soll ausschließlich deutsche Sprache verwendet werden. Auf Anglizismen und Fachterminologie wird verzichtet. Große informatische und technische Kenntnisse dürfen nicht zur Bedienung erforderlich sein. Zur Überprüfung wird eine themenfremde Testperson die Anwendung allgemein nutzen, wobei auf externe Hilfe verzichtet werden muss.

** *NFAU-1.4*: Die Möglichkeiten für Fehlentscheidungen oder Orientierungslosigkeit sollen minimiert werden. 

*** Die Dozenten sollen für die Buchung eines Experiments maximal 15 Klicks (von Anmeldung bis „Buchungsabschluss“) benötigen. Temporär nicht verfügbare Interaktionsmöglichkeiten sollen ausgegraut werden. Zu Überprüfungszwecken wird ein Testdurchlauf stattfinden, bei dem die Klicks gezählt werden und darauf geachtet wird, ob es möglich ist, nicht erreichbare Funktionalitäten aufzurufen. 
//Fehlermeldungen sollen eindeutig, ohne Interpretationsspielraum und minimal sein.

** *NFAU-1.5*: Texte und Schaltflächen sollen auf ca. 50cm Entfernung leicht lesbar und erkennbar sein. 

*** Text muss eine passende Größe und augenschonende, sowie leserliche Farbe aufweisen.

*** Schaltflächen und Symbole müssen von guter grafischer Qualität und scharf sein.

*** Zur Überprüfung wird eine Testperson die Anwendung mit einem Abstand von 50cm Entfernung zum Bildschirm nutzen. 

* *NFAU-2*: Die Eingabemöglichkeiten sollen nicht als Pop-ups erscheinen. 

*** Zur Überprüfung wird die Anwendung auf das Vorhandensein von Pop-up-Fenstern getestet.

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

* *NFAR-1*: Das System darf aufgrund von Netzwerkausfällen keinen Schaden nehmen. 
** Testweise wird beim Buchen ein Verbindungsabbruch erzwungen. 

=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

* *NFAP-1*: Die Nutzbarkeit muss gewährleistet sein, wenn alle derzeitigen Anwender gleichzeitig arbeiten wollen. 
** Überprüft wird dies durch einen Stresstest mit 10 Nutzern. 

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.

* *NFAS-1*: Das Entwicklerteam muss eine (fortgeführte) Entwicklerdokumentation bereitstellen, welche Wartung und Weiterentwicklung des Systems ermöglicht. 

* *NFAS-2*: Die Software muss auf folgenden Browsern funktionieren: 
** Edge 
** Internet Explorer (Version 11) 
** Chrome
** Firefox 
** Safari
** Zur Überprüfung muss die Anwendung in allen Browsern mit der aktuellen Version (wenn nicht anders spezifiziert), getestet werden. 

== Zusätzliche Anforderungen
=== Einschränkungen

* Die Verwaltung des Sourcecodes und der Dokumentation muss mittels *GitHub*  erfolgen. 
* *Ruby on Rails* stellt das hauptsächlich zu nutzende Framework dar. 
* Folgende Programmiersprachen sind weiterhin vorgegeben: 
** *Ruby*
** HTML/ Slim
** Sass 
** JavaScript 

=== Interface Requirements 
* Die Benutzeroberfläche soll gängige Symbole, wie beispielsweise einen Einkaufswagen für den Warenkorb, verwenden. 
* Deutsche Bezeichnungen sollen reichen (siehe Usability).
* Das Design soll an der bereits bestehenden Anwendung orientiert sein. 
* Eine offene Menüführung muss gewährleistet sein. Interaktionselemente und Links sollen nicht unnötig in Menüs versteckt sein. 


=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Der Kunde muss über eine mögliche Speicherung von Nutzungsdaten informiert werden.
* Eine etwaige Datenschutzerklärung muss beim Login vorliegen und vor der Nutzung durch Dozenten anerkannt werden. Der Verantwortliche hierbei sollte der Admin sein. 
* Keine fremden Werke dürfen fälschlicherweise als Eigene ausgewiesen werden. Urheberrecht ist zu beachten, gegebenenfalls müssen eigene Grafiken erstellt werden. 
