= Vision: {project-name}
Alena Bischoff <alena.bischoff@htw-dresden.de>; Tobias Karsch <tobias.karsch@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung

Ziel dieses Dokumentes ist es, einen genaueren Überblick über die wesentlichen Bestandteile der Änderung an der Web-App “Experimente-Management-Software” (EMS) aufzuzeigen und Informationen zu sammeln, zu analysieren und genauer zu definieren. Wir werfen einen Blick auf die einzelnen Stakeholder der Anwendung, deren Wünsche und Bedingungen. Die genaueren Details, wie die angegeben Bedürfnisse realisiert werden, finden sich in dem <<Use-Case Model: {project-name}, Use-Case Model>> und der <<System-Wide Requirements: {project-name}, System-Wide Requirements>> wieder. 


=== Zweck

Der Zweck dieses Dokuments ist es, die wesentlichen an das System gestellten Anforderungen aus Sicht der künftigen Anwender zu beschreiben. Formulierungen werden so gestaltet, dass sie für alle Stakeholder verständlich sind.


=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das Experimente-Management-System, das von Team I2 entwickelt wird. Das System wird es dem Kunden erlauben, ein Buchungssystem zu betreiben, um damit das umständliche Bestellen per E-Mail abzulösen.

=== Definitionen, Akronyme und Abkürzungen
siehe <<Glossar: {project-name},Glossar>>

=== Referenzen
based on: https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/templates/resources/vision_tpl.dot[EPL V1.0]

== Positioning
=== Fachliche Motivation
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.
Unser Kunde besitzt bereits eine Web-Anwendung, welche es ihm und seinen Kollegen (Dozenten) möglich macht, physikalische Experimente in passenden Kategorien zu betrachten. Details und Bestandteile können angesehen und eine Karteikarte generiert werden, welche genau diese Informationen druckbar macht, um diese physisch vorliegen zu haben.
Für die Dozenten ist es wichtig, bei unserem Kunden ihre Wahl an durchzuführenden Experimenten für die kommende Woche in Auftrag zu geben. Dies geschieht bisher formlos per Mail an den Kunden. 

Diese Methode ist sehr unübersichtlich, da die einzelnen Mails der Dozenten ausgewertet werden müssen und keine einheitliche Bestellvorlage verwendet wird. Die Mails müssen händisch nach Wochentag und Dozent sortiert werden, was einen deutlichen Mehraufwand darstellt. 


Um diesen Mehraufwand zu umgehen, möchte der Kunde die Möglichkeit, Experimente in einen “Warenkorb” hinzuzufügen. In diesem sollen je Vorlesung verschiedene Experimente hinterlegt und als Auftrag bestellt werden können. Schlussendlich sollen diese Daten dann automatisiert abrufbar gemacht werden und zur einfachen Planung der Bestellungen als in Tage gegliederte Wochen pro Dozent angezeigt werden. 


Ebenfalls soll die Möglichkeit einer Auswertung der vergangenen Bestellungen ermöglicht werden. Dies ist wichtig, um herauszufinden, welche Experimente besonders oft gebucht werden, um bspw. den Verschleiß der Geräte vorauszusagen und in Folge dessen mehr Geräte oder Instrumente einzukaufen.

Als Zusatzziel gilt die Verwaltung der in den Experimenten enthaltenen Bilder. Bei der Anschaffung von neuen Instrumenten für die Experimente müssen auch die Bilder entsprechend erneuert werden. Dabei soll, um Konsistenz zu bewahren, die Bezeichnung der Bilder gleich bleiben, das Bild jedoch in Datei und Reihenfolge anpassbar gemacht werden. 

=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:


[cols="1,3"]
|===
|Das Problem 
a|

* Dozent muss für die Folgewoche eine Mail verfassen, welche seine gewünschte Experimente-Auswahl enthält
* Jede Änderung erfordert das erneute Senden einer Mail
* Kunde muss händisch E-Mails der Dozenten auswerten und sortieren; sich selbst einen Plan der benötigten Experimente je Wochentag erarbeiten 


|Betrifft 
a|	

* Kunde
* Dozenten

|Die Auswirkung davon ist 
a|


* Dozenten haben verschiedene “Templates” für das Versenden ihrer Wünsche per Mail → kein normales “Kopieren” möglich 
* Keine automatische Sortierung pro Tag; muss händisch durch Kunden in richtige Reihenfolge gebracht werden
* Unnötiges Aufkommen von vielen Mails 
* Es ist nicht ersichtlich, wessen Wochenplan noch nicht aufgegeben wurde	


|Eine erfolgreiche Lösung wäre 
a|


* Warenkorb-Funktion: Die Experimente können nach Festlegung der Voreinstellungen für eine Vorlesung in einen Warenkorb abgelegt werden. Anschließend kann die Reihenfolge noch angepasst werden. Nach erfolgreicher Buchung werden sie dem persönlichen Journal hinzugefügt.
* Journal-Funktion: Buchungsübersicht des Dozenten, wo er alle vergangenen Buchungen einsehen und aktuelle Buchungen anpassen kann
* Dozentenwochen-Funktion: Buchungsübersicht des Admins, wo er alle Buchungen pro Dozent und sortiert je Wochentag einsehen kann

|===


=== Product Position Statement 
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
|Für

|Dozenten,
Admin [Kunde] 

|Der / Die

a|


* Dozenten: 
** … die Experimente für die kommenden Vorlesungen buchen wollen
* Admin: 
** ... der einsehen will, welche Experimente gebucht wurden
** … der einsehen will, in welchem Umfang die Experimente in der Vergangenheit gebucht wurden


|Das Produkt / Die Lösung ist eine | … Erweiterung der Web-Anwendung “Experimente-Management-System"

|Welche	|… die Buchung von Experimenten und Einsicht der Buchungen sowie deren Historie ermöglicht 

|Im Gegensatz zu	|… der Buchung über E-Mail und der manuellen Historie sowie Aufbereitung
|Unser Produkt|	… ermöglicht die einfache Bestellung von Experimenten und Generierung eines für den Anwender optimierten Buchungsplans, sowie eine Übersicht der bisherigen Buchungen

|===


<<<
==	Stakeholder Beschreibungen
===	Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
|Name|	Beschreibung	| Verantwortlichkeiten

|Admin/ +
Kunde	a|

* Mitarbeiter der HTW
* Vorlesungsassistent im Bereich Energietechnik/Physik
* Versorgt Dozenten mit Experimenten (“Interner Dienstleister”) 
* Möchte seine wöchentliche Arbeit optimieren 
* Möchte, dass die Dozenten möglichst minimalen Aufwand haben	a|

* Stellt Experimente nach Bestellung bereit 
* “Verwalter” des Webtools – stellt Informationen zu den Experimenten bereit 
* Führt diese durch 
* Kümmert sich um Instandhaltung der Experimentiergeräte
* Verantwortlicher für Datenschutzaufgaben (Datenschutzerklärung verfassen & herausgeben)

|Dozent a|

* Mitarbeiter im Bereich Energietechnik/Physik der HTW 
* Hat Interesse an Experimenten für seine Vorlesung 
* Interesse an vereinfachter Buchung für bestimmten Zeitslot 
* Ist Frontend-Benutzer des Systems a|

* Pünktlich Experimente buchen 
* Ort und Zeit muss gewährleistet werden 

|TAVM (Herr Hornoff)
// Bezeichnung Stakeholder?
a| * Betreuer der VM a| * Gewährleistung eines Arbeitsumfeldes für uns


|Rechenzentrum der HTW a| * Ist "Standort" der Nutzeranwendung und Datenbank a| * Muss die Bereitstellung der Anwendung sicherstellen


|===


=== Stakeholderanalyse

==== Kunde

Das Hauptinteresse des Kunden ist es, die Dozenten durch das System zufrieden zustellen. Seine Angst, dass das System auf Ablehnung durch die Dozeten trifft, ist sehr groß. Er spricht sich aber leider nur sehr wenig oder teils gar nicht mit den Dozenten ab. Er versucht die Wünsche und die Probleme der Dozenten selbst zu formulieren. Dadurch ist er oft verunsichert in seinen Forderungen oder versucht das System durch ständige Änderungen der Forderungen für die Dozenten zu optimiern. Auch die Tatsache, dass es sich um fünf Dozenten handelt und er versucht es jedem einzelnen recht zu machen, stellt ihn immer wieder vor Herausforderungen, was für uns bedeutet, dass anfängliche beschlossene Umsetzungen wieder geändert werden müssen. 

==== Dozenten 

Mit den Dozenten hatten wir außer Frau Dr. Krwietz keinen Kontakt. Ihr Hauptziel ist es, dass das System Sie bei Ihrer Arbeit unterstützt und auch weiterhin all Ihre Arbeitspraktiken durch das System gewährleistet sind. Sie ist unsrem System sehr wohlgesonnen eingestellt und lässt sich auf das System ein. Auch ein umdenken zu Ihrer alten Arbeitsweise ist bei Ihr erkennbar. Es gibt aber anscheinend Dozenten die dem System nicht positiv eingestellt sind. Ihre Ziele sind es das System verwenden zu können ohne sich mit ihm beschäftigen zu müssen. Es muss sehr intuitiv sein. Diese Anahme besteht aber nur auf Höhrensagen. 
=== Benutzerumgebung
//Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
//. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
//. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
//. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
//. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

//Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.
[%header, cols="1,1"]
|===
|Kunde
|Dozent

|*Ist-Zustand:* Kunde erhält Mails mit Bestellwünschen der einzelnen Experimente pro Woche. Daraufhin druckt sich der Kunde die Wünsche aus. Unübersichtliches, uneinheitliches und zeitintensives Auswerten der einzelnen Dozentenwünsche.  
|*Ist-Zustand:* Die Dozenten suchen sich für Ihre Vorlesungen Experimente aus dem EMS aus und senden Ihre Experimentwünsche dem Kunden per Mail zu. Hierbei fallen zusätzliche Arbeiten an, da sie ihre Experimente zeitlich organisieren müssen.
|*Soll-Zustand:* Der Kunde kann sich im EMS direkt einen Wochenplan für jeden Dozenten ausdrucken lassen. Es soll einfacheres und komfortableres Arbeiten ermöglicht werden.  
|*Soll-Zustand:* Die Dozenten können ihre Wunschexperimente direkt im EMS pro Vorlesung buchen.

|===





== Produkt-/Lösungsüberblick
=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.


[%header, cols="4,1,4,1"]
|===
|Bedarf|	Priorität|	Features|	Geplan-tes Release


|Einheitliches Buchungssystem für EMS mit Buchungsverwaltungsfunktionalitäten| Hoch a|* *Voreinstellung:*  Festlegung der Buchungsdetails vor Buchungsbeginn
* *Warenkorb:* Experiment in Warenkorb legen und evtl. Reihenfolge anpassen
* *Journal:* Einsehen vergangener und Bearbeiten aktueller Buchungen durch den Dozenten
* *Dozentenwoche:* Einsehen der Buchungen je Kalenderwoche und pro Dozent 
 | xx

|Benutzerverwaltung der einzelnen Anwender |Hoch | *Login:* Erweitern auf dozentenspezifische Accounts | xx
|Einfachere Auswahl eines Geräts bei der Erstellung eines Experiments| Mittel |
*Experimentfeld "Geräte" Anpassung*: Ansicht der Geräte für Experimente übersichtlicher gestalten | xx
|Buchungshäufigkeit auswerten |Mittel |*Statistik:* bei der Experimente-Auswahl, um die bestellten Experimente einsehen zu können |xx
|Fehlerbehebung |Niedrig a|* *Verwaltung der Bilder:* Bilder in Experimenten können ersetzt werden, Reihenfolge wird einbehalten
* *Bugfix bei Experimentfeld "Gefahren":* Bei der Anzeige von Textfeldern werden diese ineinander geschoben, dies soll behoben werden   |xx


|===


== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren

//Hinweise:
//. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
//. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
//. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
//. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
//. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
|Anforderung|	Priorität|	Geplantes Release
|Einfache Bedienbarkeit |Hoch |xx
|Im Handbuch soll erklärt werden wie ein Update von Ruby on Rails durchzuführen ist |Hoch |xx
|Der Kunde erhält ein Admin Konto und ein Dozenten Konto |Hoch |xx
|Hilfestellung / Kundenfreundliche Dokumentation |Niedrig |xx
|===

== Aussicht für zukünftige Projekte
[.text-left]
#Einige Ideen des Teams wurden vom Themensteller abgelehnt. Da das Team I2 dennoch von der Notwendigkeit und dem Nutzen dieser skizzierten Funktionen für die Vorlesungsassistenz überzeugt ist, wollen wir sie nicht in in Vergessenheit geraten lassen. Zukünftige (studentische) Projektteams sollen davon profitieren können. Hier ist der Platz, sie festzuhalten.#

Dienlich zum Verständnis ist bspw. das Lesen des Protokolles zu TS-M3 vom 07.01.2021 (Word-Dokument; Ansprechpartner: {GM}, {TKa})

* Auswahl des Studienganges bei jeder Buchung ist umständlich – das Problem wurde auf Später vertagt, wir entwickeln die Lösung nach den besprochenen Wireframes (Stand: 31.01.2021)
* Statistik/Historie: Ein Date-Picker-Mechanismus sollte von uns im Deployment hinterlegt worden sein. Darauf kann evtl. bei einer Neugestaltung der Historien-Ansicht zurückgegriffen werden. Wir halten den bisherigen Entwurf als Aufgliederung in zwei Semester als verbesserungswürdig. (Stand: 31.01.2021)
* Das Projekt soll der Öffentlichkeit zugänglich gemacht werden, was über den Gast Zugang realiseirt werden soll. Hierbei sind große Interessen auf die Schützung der Personenbezogenen Daten so wie der Experimente Daten zu legen. (Stand: 27.04.2021)
* *Kopierfunktion:* Eine Kopierfunktion zur Reproduktion aller Buchungen eines vergangenen Semesters wurde gewünscht. Wir sahen hier einen Zielkonflikt und einigten uns mit allen Stakeholdern darauf, dass wir das bisher entworfene Buchungssystem entwickeln (vgl. *I03*).
//Link?
Sollte diese Funktion in der Zukunft erneut gefordert werden, so sind hier unsere Überlegungen dazu aufgelistet:

[%header, cols="1,1"]
|===
|Agreement (Stand: 07.01.2021)|	Probleme, die zu adressieren sind
a|* Problem wurde von allen Parteien erkannt
* Die Kopierfunktion entspringt der *grundsätzlichen Motivation* des Projektes: Den Dozenten soll die *Arbeit im höchstmöglichen Umfang vereinfacht werden*. Deshalb soll der einmal bestrittene Ablauf von Experimenten in einem Semester leicht wieder auf ein Neues anzuwenden sein.
* Erkenntnis aus dem derzeitigen Projekt: Um Statistik zu erhalten, müssen Dozenten immer wieder neu buchen -> muss den Dozenten klar gemacht werden
* Dozent muss sich SEINE Woche drucken können -> braucht auch Zugang zu SEINER Dozentenwoche (Journal als Historie, Dozentenwochen aber auch) 
a|* Datumsanpassung jeder kopierten Vorlesung ist erforderlich
* Was ist beim Wechsel Winter- zu Sommersemester? 
* Je mehr kopiert werden soll (einzelne VL-Tage-Wochen-Semester), desto mehr Angaben muss der User wieder anpassen
* Je einfacher die Kopierfunktion wird, desto mehr Daten fallen weg: MO der 06. um 11:10 wird zu MO
* Wochentage ändern sich von Semester zu Semester! (Feiertage etc.) + Unterschiedlicher Fortschritt in den Vorlesungen

|===

=== Finale Zukunftsanforderungen

NOTE: Die unten genannten Anforderungen resultieren aus dem Themenstellermeetings am 10.06.2021 und 23.06.2021 und sind somit endgültig. 

* das System soll den User informieren, wenn sich an einer bereits gedruckten Dozentenwoche etwas geändert hat 
* bei der Bearbeitung einer bereits getätigten Buchung soll es möglich werden, auch die Voreinstellungen anzupassen 
* im Journal soll es möglich werden, explizite Buchungen anhand einer Filterfunktion zu finden 
* die Auswertung der Buchungshäufigkeit der Experimente soll anhand der Statistik umgesetzt werden
* eine Verwaltung der Studiegänge soll (ähnlich wie die der Experimente) ermöglich werden
* eine weitere Rolle "Assistent" soll vergeben werden können, welche die Wochenpläne einsehen kann aber keine Verwaltungsrechte (wie der Admin) hat
* visuelle Anpassungen:
** "Buchung starten"-Button soll grün werden
** "Buchung abschließen"-Button soll zu "Zum Warenkorb" umbenannt werden
** "Änderung speichern"-Button soll zu "Kommentar speichern" umbenannt werden
** einheitliche Größe der drei Sidebar-Buttons während einer Buchung umsetzen
** "Buchung abbrechen"-Button soll rot werden
** "Manuell Experiment hinzufügen"-Button soll zu "Freies Experiment hinzufügen" umbenannt werden
* Button "Experiment hinzufügen" im Warenkorb hinzufügen - leitet zurück an die Stelle in der Experimenteübersicht, an der zum Warenkorb gegangen wurde
* bei Zeitraumauswahl für die Dozentenwochenansicht soll standardmäßig die nächste Kalenderwoche angezeigt werden
* während eines Buchungsprozesses soll der Button "Karteikarte öffnen" der Experimente ausgeblendet werden 
