source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'rails', '~> 5.2.2'
gem 'sqlite3'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks', '~> 5'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'jquery-rails'
gem 'jquery-ui-rails'

gem 'slim-rails'
gem 'bootstrap'
gem 'font-awesome-sass', '~> 4.7.0'
gem 'bootswatch'
gem 'validate_url'
gem 'devise'
gem 'simple_form'
gem "paperclip", "~> 6.0.0"
gem "cocoon"
gem 'will_paginate'
gem 'will_paginate-bootstrap4'
gem 'listen'

gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'spring'
  gem 'rubocop', require: false
  gem 'bundler-audit', require: false
end

group :development do
  gem "capistrano", "~> 3.10", require: false
  gem "capistrano-rails", "~> 1.4", require: false
  gem 'capistrano-rvm', github: 'capistrano/rvm', require: false
  gem 'capistrano-scm-copy', require: false
end

group :test do
  gem 'faker'
  gem 'fabrication'
  gem 'poltergeist'
  gem "capybara"
  gem 'timecop'
  gem 'webmock'
  gem "test-unit"
  gem "minitest"
  gem 'rspec-core'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'vcr'
  gem 'fuubar'
  gem 'database_cleaner'
  gem 'simplecov', require: false
end
