= Projektplan: {project-name}
Tim Würzburg <tim.wuerzburg@htw-dresden.de>; Tobias Karsch <tobias.karsch@htw-dresden.de>; Gregor Müller <gregor.mueller@htw-dresden.de>;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

== Einführung
//Briefly describe the content of the project plan.
Wir (Team I2) orientieren uns bei unserem Projekt am Vorgehensmodell Open Unified Process.
Das Projekt umfasst die vier Phasen:

* Inception
* Elaboration
* Construction
* Transition

Der Projektplan wird fortlaufend ergänzt und verfeinert. Verantwortlich dafür sind die Projektmanager.

== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.

Unser gesamtes Team und die Personen, die auch direkt oder indirekt mit dem Projekt in Verbindung stehen, werden in der <<Verantwortlichkeiten: {project-name},Rollenübersicht>> vorgestellt. Hier findet man auch eine Übersicht, welche unterschiedlichen Rollen und zusätzlichen Aufgaben die einzelnen Gruppenmitglieder innehaben.

Da während unseres Projekts die Corona-AHA Regeln gegolten haben, wurden auf physische Treffen komplett verzichtet. Die komplette Kommunikation lief über die Programme *Whatsapp*, *Discord* und *MS-Teams*.

Der rote Faden unsrer Arbeit war, dass die Projektmanager einen Iterationszeitraum bestimmten und versuchten, die zu bewältigende Arbeit in Meilensteinen, Iterationsziele und Aufgaben aufzugliedern. Die Aufgaben wurden dann an die gesamten Gruppenmitglieder verteilt und durch die Gruppe überwacht. Wenn einzelnen Personen Probleme bei ihren zugewiesnen Aufgaben, egal welcher Art, hatten, wurde dies in den Weeklys aufgegriffen und versucht die Probleme zu lösen.

Siehe *<<Verantwortlichkeiten: {project-name}, Rollenübersicht>>*

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

=== Management practices

https://www2.htw-dresden.de/~anke/openup/publish.openup.base/customcategories/management_practice_list_8D917129.html?nodeId=770581c6[Management Practices OpenUP]

* *Iterative Development:* Plan Iteration - Manage Iteration - Assess Results

Das Team führt 14-tägige Iterationen durch. Wir nutzen ein modifiziertes https://github.com/Schmiddl99/experimenteverwaltung-i2/projects/3[Scrum-Board] auf GitHub für Planung und Steuerung jeder Iteration. Iterationen werden in ALLEN Phasen des Projektes generell mit der Klassifizierung I01, I02, ... I[n] benannt. Dafür haben wir uns entschieden, da die OpenUP-Meilensteine nicht zwangsweise am Ende einer Iteration, sondern während der Arbeit erreicht wurden, was eine Aufteilung in I-, E-, C- und T-Phasen erschwerte.
Regeln zum Umgang mit den Aufgaben (Issues) und mit Pull Requests sind im https://github.com/Schmiddl99/experimenteverwaltung-i2/wiki/Iteration-Planning[Wiki] festgehalten.
Der Fortschritt einer jeden Iteration bildet sich durch das "Wandern" der Aufgaben von der Spalte "Work Item List" in die Spalte "DONE" ab. Zu Beginn einer jeden Iteration wird die Work Item List wieder gefüllt. Der globale Projektfortschritt wird außerdem mithilfe des ESSENCE Navigator Tools sowie durch die Definition und Messung zu erreichender OpenUP-Meilensteine veranschaulicht.

Das Ende einer jeden Iteration wird mit einer *Review* und einer *Retrospective* abgeschlossen. Dabei ist das gesamte Team mit einzubeziehen!

* Wöchentliche Besprechungen (*Weekly*) sind obligatorisch.
** Dabei hat sich die Moderation durch einen zuvor bestimmten Redeführer etabliert
** Die Agenda wird im Voraus von den PM entworfen und der Gruppe zugesandt
** Ein "Weekly Scrum" wird zu Beginn eines jeden Weekly durchgeführt
*** Dauer insgesamt max. 10 min
*** Jedes Teammitglied erläutert knapp woran er/sie gerade arbeitet bzw. in der vergangenen Woche gearbeitet hat
*** Jedes Teammitglied berichtet, was sie/ihn aktuell an der Arbeit behindert
*** Äußerungen werden nicht kommentiert

* *Team Change Management:* Diese OpenUP-Praktik wird durch unser https://github.com/Schmiddl99/experimenteverwaltung-i2/projects/3[Scrum-Board] auf GitHub realisiert. Änderungsanfragen am Scope für diese/folgende Iteration(en) sowie Change Requests an Work Items werden durch das Anlegen eines neuen Issues mit entsprechender Beschreibung nach den Regeln im https://github.com/Schmiddl99/experimenteverwaltung-i2/wiki/Iteration-Planning[Wiki] vorgenommen. Die PM müssen zeitnah darauf reagieren.

* *Risk-Value Life Cycle:* Im OpenUP ermöglicht diese Praxis das systematische Erkennen und Reagieren auf Risiken. Uns dient sie in erster Linie zur internen Bewertung des Projektfortschritts. Die definierten Meilensteine - LCO, LCA, IOC, PRM - werden in jeder Iteration Review überprüft. 

Die Position der Stakeholder wird dabei zu gleichen Teilen, aber auf indirekte Art und Weise berücksichtigt. Die Bewertung der Risiken und dem bisherigen Wertzuwachs - kurzum des Projektzustands - wird in den Stakeholdermeetings erfragt. Die Erläuterung der OpenUP-Praktiken und -Begrifflichkeiten gegenüber dem Themensteller erfolgt jedoch aufgrund der begrenzten Zeit nicht. Die Meetings sollen stattdessen noch stärker dem Wertzuwachs am eigentlichen Produkt dienen.

* *Whole Team:*

** Workshops für teaminternen Wissensaustausch werden ad-hoc durchgeführt (z.B. für die Arbeit in GitHub und Ruby). Alle Teammitglieder sollen vom Wissen der Anderen profitieren können

*** Der erste Workshop zum Thema "GitHub" wurde am 21.12.2020 von {RB}, {TKI} und {GM} durchgeführt (Siehe <<Iteration Plan 02: {project-name}, I02>>)
** Konventionen und Anleitungen werden im GitHub-Wiki geteilt: https://github.com/Schmiddl99/experimenteverwaltung-i2/wiki[Wiki]

* Das *Qualitätsmanagement* wird durch die Verantwortliche {AB} gestaltet und durchgeführt

=== Technical Practices
https://www2.htw-dresden.de/~anke/openup/publish.openup.base/customcategories/technical_practice_list_E425C20F.html?nodeId=cd065eb4[Technical Practices OpenUP]

* *Shared Vision*: Diese OpenUP-Praktik verbessert die Akzeptanz des späteren Produktes durch alle Stakeholder. In unserem Fall strebten wir die Übereinstimmung über die <<Vision: {project-name}, Vision>> und die damit beschriebene Opportunity gemeinsam mit dem Themensteller an. Das Team konnte diese Übereinstimmung in <<Iteration Plan 03: {project-name}, Iteration I03>> erreichen.

* *Use Case Driven Development*: OpenUP empfiehlt die Zugrundelegung eines 
<<Use-Case Model: {project-name}, Use Case Models>>
sowie von <<System-Wide Requirements: {project-name}, System-Wide Requirements>>
zur Beschreibung, Gliederung und Auswertung der erhobenen Anforderungen. Durch die Nutzung dieser Praktik versprechen wir uns eine effizientere Umsetzung und ein höheres Erfolgspotential des gesamten Projektes.

* *Evolutionary Architecture*: Das Architecture Notebook
//Link!!
wird in Abhängigkeit des Projektzustandes bearbeitet. Bei dieser schrittweisen Ausarbeitung und Verfeinerung der Architektur wird darauf geachtet, die identifizierten Risiken zu berücksichtigen und, wenn möglich, mit den Architekturmechanismen adäquat auf sie zu reagieren.

//Hier solltet ihr in SEII weitere angewandte Praktiken beschreiben (siehe https://www2.htw-dresden.de/~anke/openup/publish.openup.base/customcategories/technical_practice_list_E425C20F.html?nodeId=cd065eb4) - TKa

[#project-plan-meilensteine-und-ziele]
== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase


[%header, cols="1,3a,2"]
|===
| Iteration
| Primary objectives (risks and use case scenarios)
| Scheduled start or milestone

| I01

| * Gruppenfindung, Team kennenlernen
* Rollenverteilung, Namen der Projektmanager übermitteln
* Aufgabe kennenlernen
* Kontakt zu Themensteller aufnehmen
* TS-M1
* Kontakt zu Coach

| 16.11.2020-16.12.2020

| I02
|<<Iteration Plan 02: {project-name}, Iterationsplan I02>>
| 17.12.2020-31.12.2020

| I03
|<<Iteration Plan 03: {project-name}, Iterationsplan I03>>
| 07.01.2021-21.01.2021

| I04
| * Erarbeitung des Domänenmodells
* Überarbeitung der <<Use-Case Model: {project-name}, Use Cases>>
* Überarbeitung der <<Test Cases: {project-name},Test Cases>>
* Anfertigung des Beleges für das Modul: Überprüfung der Dokumente (siehe <<QM Regeln, QM>>)
//* Ausscheiden der Teilnehmer {JS}, {TW}, {TKa} aufgrund Beendigung des Moduls I925 Requirements Engineering
| 22.01.2021-04.02.2021

|===

=== Bemerkungen zum weiteren Projektverlauf
* Im Team herrscht Einigkeit darüber, dass Serveroptimierung nicht in unseren Aufgabenbereich fällt. Vom Vorhandensein ausreichender technischer Ressourcen und der Wartung des Fakultätsservers durch die Verantwortlichen außerhalb des Projektes wird ausgegangen.
* In das Benutzerhandbuch ist eine Anleitung zum Systemneustart zu integrieren
* Bei dem Wechsel von SE I zu SE II wurde das Team von {tka}, {tw}, {js}, {tki} und {ab} aus privaten oder Lehrplangründen verlassen. Der Abschied verlief bei jedem Teammitglied geregelt und auf eigenen Wunsch hin ab. Jeder Verlust wurde vom restlichen Team sehr bedauert. 
* Um diese Unterbesetzung auszugleichen wurde dem Team {pg} zugewiesen, welcher mit großer Freude aufgenommen wurde und sich selbständig in das Projekt einarbeitete. 

Bei der Planung zukünftiger Iterationen und ihrer Ziele sind diese Punkte zu verwirklichen. 

== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.
Das Deployment des EMS wird in großen Teilen von dem bereits bestehenden System übernommen. Durchgeführt wird es hauptsächlich vom Deployment Engineer. Damit dieser Prozess trotzdem für alle am System beteiligten Entwickler zugänglich ist, wurde es im <<Deployment: {project-name}, Abschnitt Deployment>> dokumentiert.

== Erkenntnisse (Lessons Learned)

=== SE I
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.

* Kommunikation mit den Stakeholdern ist der Knackpunkt für die Anforderungsanalyse und das tiefgründige gegenseitige Verständnis initial der wichtigste Faktor.
* Bestimmung eines Redeführers und Vorbereitung der Tagesordnung machen Meetings deutlich zeiteffizienter.
* Wissensweitergabe im Team lässt sich über selbstorganisierte Workshops sehr gut realisieren - von der Erfahrung einzelner Teammitglieder können so alle profitieren.

=== SE II

* Es gibt Differenzen zwischen dem theoretischen Verständnis bezüglich der agilen Softwareentwicklung und ihrer Umsetzung. 
* Der Kunde muss für sein System selbst die Verantwortung tragen und nicht das Entwickler-Team. Es reicht aus, den Kunden auf fragwürdige Anforderungen hinzuweisen, sie werden aber auf Wunsch umgesetzt, solange sie ethisch vertretbar sind.
