= Verantwortlichkeiten: {project-name}
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]

== Verteilungskriterien

Die Aufgaben wurden hauptsächlich nach Interessens- und Expertisengebieten verteilt. Das Team einigte sich darauf, das der Rollenverantwortliche sich hauptsächlich um die Dokumentationspflichten und Arbeitsprirorisierung kümmerte, er aber immer von anderen Teammitglieder bei der eigentlichen Aufgabe unterstützt wird. So konnte wir eine perfekte Mischung aus Rollenspezialisierung und Informationsaustausch erreichen. 

|===
|*Name* |*Rolle* |*Anmerkung* |*Letze Änderung*
|Tobias Karsch

Ausscheidend nach SE I
|Project Manager (SE I)

Analyst (zus.)
|Standardmäßig Protkoll-verantw.

ESSENCE-Navigator
|18.01.2021

|Tim Würzburg

Ausscheidend nach SE I
|Project Manager (SE I)

Risk-List (zus.)

Analyst (zus.)
|Standardmäßig Protkoll-verantw.

Kontaktperson Themensteller
|20.01.2020

|Gregor Müller 
|Tester (SE I)

Developer (zus.) (SE I)

Project Manager (SE II)

QM-Beauftragter (zus.) (SE II)

Risk-List (zus.) ( SE II)

|Übernimmt PM in SE II

Redeführer in Meetings (SE I)
|05.04.2021

|Julius Schmidt

Ausscheidend nach SE I
|Analyst
|Terminplaner (Doodle)

Microsoft-Teams Verantwortlicher
|14.01.2021

|Richard Böhme
|Developer

GitHub Verantwortlicher (zus.)

Architect (zus.) (SE II)

Deployment (zus.) (SE II)

Tester (zus.)
|Deployment (virtuelle Maschine)

GitHub Workshop

Ruby on Rails Workshop
|05.04.2021

|Alena Bischoff

Ausscheidend nach SE I
|QM-Beauftragte

Developer (zus.)

Tester (zus.)
|Erstellt Wireframes und UML-Diagramme
|05.04.2021

|Taejun Kim

Ausscheidend nach SE I
|GitHub-Verantwortlicher

Developer (zus.)

Architect (zus.)
|GitHub-Kontrolleur
|05.04.2021

|William Elsner
|Architect 

Tester (zus.)

Developer (zus.) (SE II)
|Glossar Betreuung
|05.04.2021

|Piet Gutsche

Projekt-Einstieg SE II
|Tester

Analyst (zus.)

Developer (zus.)
|GitHub-Kontrolleur
|05.05.2021

|Vincent Thelang

vincent@vincent-thelang.de
|Mitglied des Vorgängerteams -
|Steht zur Seite bei Fragen

bietet Einführung zu Ruby on Rails an
|02.12.2020
|===
